### ISSUE TITLE
Docker rule fails with RuntimeError: Cannot handle .xz compression: xz not found.

### ISSUE THREAD

**Issue by tsuna** [bazelbuild/homebrew-tap#36]
Trying to build `kops` after installing the tap:

```
$ bazel build --action_env=PROTOKUBE_TAG=1.12.0-alpha.1 --platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 //images:protokube.tar
[...]
ERROR: /Users/tsuna/go/src/k8s.io/kops/images/BUILD.bazel:21:1: ImageLayer images/protokube-image-layer.tar failed (Exit 1) build_tar failed: error executing command bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar '--flagfile=bazel-out/darwin-fastbuild/bin/images/protokube-image-layer.args'

Use --sandbox_debug to see verbose messages from the sandbox
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_tsuna/492ffd9dfe7b043a21dbad24206d7773/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 423, in <module>
    main(FLAGS(sys.argv))
  File "/private/var/tmp/_bazel_tsuna/492ffd9dfe7b043a21dbad24206d7773/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 416, in main
    output.add_deb(deb)
  File "/private/var/tmp/_bazel_tsuna/492ffd9dfe7b043a21dbad24206d7773/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 308, in add_deb
    current.data = self._xz_decompress(current.data)
  File "/private/var/tmp/_bazel_tsuna/492ffd9dfe7b043a21dbad24206d7773/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 352, in _xz_decompress
    return decompress(data)
  File "/private/var/tmp/_bazel_tsuna/492ffd9dfe7b043a21dbad24206d7773/sandbox/darwin-sandbox/1/execroot/__main__/bazel-out/host/bin/external/io_bazel_rules_docker/container/build_tar.runfiles/io_bazel_rules_docker/container/build_tar.py", line 333, in _xzcat_decompress
    raise RuntimeError('Cannot handle .xz compression: xz not found.')
RuntimeError: Cannot handle .xz compression: xz not found.
Target //images:protokube.tar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.729s, Critical Path: 0.66s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

I do have the `xz` package installed via Homebrew, but by default it only tries the `lzma` Python module and otherwise expects a `xz_path` flag to be passed to point to the `xz` binary (I'm still trying to figure out how to pass that flag).

JFYI, I have:
```
$ bazel version
Build label: 0.21.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 19 12:57:09 2018 (1545224229)
Build timestamp: 1545224229
Build timestamp as int: 1545224229
```

**Comment by tsuna** [comment]
See the above issue if you run into this.
